-- 00002_feeding.sql

-- Новые поля для кормления
ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS free_food_at TIMESTAMPTZ DEFAULT '1970-01-01T00:00:00Z',
  ADD COLUMN IF NOT EXISTS ads_today INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ads_today_date DATE NOT NULL DEFAULT CURRENT_DATE;